float32 X
float32 y

# -- In LSB units of 0.1 microdegrees (unless a zoom is employed)

# -- Nodes with X,Y content
# node-XY1
# -- node is within 5.11m of last node
# node-XY2
# -- node is within 10.23m of last node
# node-XY3
# -- node is within 20.47m of last node
# node-XY4
# -- node is within 40.96m of last node
# node-XY5
# -- node is within 81.91m of last node
# node-XY6
# -- node is within 327.67m of last node
